In [86]:
# N과 M(1)
from itertools import permutations
from itertools import combinations

# N = 4
# M = 4
N, M =map(int, input().split())

arr = list(range(1, N+1))

k = list(permutations(arr, M))
for i in k:
    print(' '.join(map(str, i)))

1 2 3 4
1 2 4 3
1 3 2 4
1 3 4 2
1 4 2 3
1 4 3 2
2 1 3 4
2 1 4 3
2 3 1 4
2 3 4 1
2 4 1 3
2 4 3 1
3 1 2 4
3 1 4 2
3 2 1 4
3 2 4 1
3 4 1 2
3 4 2 1
4 1 2 3
4 1 3 2
4 2 1 3
4 2 3 1
4 3 1 2
4 3 2 1


In [90]:
from itertools import combinations

N, M = map(int, input().split())
arr = list(range(1, N+1))

k = list(combinations(arr, M))

for i in k:
    print(' '.join(map(str, i)))

[1, 2, 3, 4]
1 2
1 3
1 4
2 3
2 4
3 4


In [118]:
from itertools import product

N, M = map(int, input().split())

# N = 3
# M = 2

a = list(product(range(1, N+1), repeat=M))

for i in a:
    print(' '.join(map(str, i)))

1 1 1
1 1 2
1 1 3
1 2 1
1 2 2
1 2 3
1 3 1
1 3 2
1 3 3
2 1 1
2 1 2
2 1 3
2 2 1
2 2 2
2 2 3
2 3 1
2 3 2
2 3 3
3 1 1
3 1 2
3 1 3
3 2 1
3 2 2
3 2 3
3 3 1
3 3 2
3 3 3


In [119]:
from itertools import combinations_with_replacement

N, M = map(int, input().split())
arr = list(range(1, N+1))

k = list(combinations_with_replacement(arr, M))

for i in k:
    print(' '.join(map(str, i)))

1 1 1
1 1 2
1 1 3
1 2 2
1 2 3
1 3 3
2 2 2
2 2 3
2 3 3
3 3 3


In [167]:
import numpy as np

a_list = [[0, 3, 5, 4, 6, 9, 2, 7, 8], 
           [7, 8, 2, 1, 0, 5, 6, 0, 9], 
           [0, 6, 0, 2, 7, 8, 1, 3, 5], 
           [3, 2, 1, 0, 4, 6, 8, 9, 7], 
           [8, 0, 4, 9, 1, 3, 5, 0, 6], 
           [5, 9, 6, 8, 2, 0, 4, 1, 3], 
           [9, 1, 7, 6, 5, 2, 0, 8, 0], 
           [6, 0, 3, 7, 0, 1, 9, 5, 2], 
           [2, 5, 8, 3, 9, 4, 7, 6, 0]]

true_list = [1,2,3,4,5,6,7,8,9]
# for i in a_list:
#     if len([v for v in i if v==0])==1:
#         print(i)
#         print(i.index(0))
    
# for i in a_list:
#     if len([v for v in i if v==0])==1:
#         print(i)
#         print(i.index(0))
#         print([v for v in true_list if v not in i and v in true_list])
#         i[i.index(0)] = [v for v in true_list if v not in i and v in true_list][0]
#         print(i)

for i in range(9):
    if len([v for v in a_list[i] if v==0])==1:
        a_list[i][a_list[i].index(0)] = [v for v in true_list if v not in a_list[i] and v in true_list][0]
print(a_list)

b_list = np.transpose(a_list)
print(b_list)

# 너무 복잡하게 풀어서 아래에서 다시!

[[1, 3, 5, 4, 6, 9, 2, 7, 8], [7, 8, 2, 1, 0, 5, 6, 0, 9], [0, 6, 0, 2, 7, 8, 1, 3, 5], [3, 2, 1, 5, 4, 6, 8, 9, 7], [8, 0, 4, 9, 1, 3, 5, 0, 6], [5, 9, 6, 8, 2, 7, 4, 1, 3], [9, 1, 7, 6, 5, 2, 0, 8, 0], [6, 0, 3, 7, 0, 1, 9, 5, 2], [2, 5, 8, 3, 9, 4, 7, 6, 1]]
[[1 7 0 3 8 5 9 6 2]
 [3 8 6 2 0 9 1 0 5]
 [5 2 0 1 4 6 7 3 8]
 [4 1 2 5 9 8 6 7 3]
 [6 0 7 4 1 2 5 0 9]
 [9 5 8 6 3 7 2 1 4]
 [2 6 1 8 5 4 0 9 7]
 [7 0 3 9 0 1 8 5 6]
 [8 9 5 7 6 3 0 2 1]]


In [168]:
import numpy as np

sudoku = [[0, 3, 5, 4, 6, 9, 2, 7, 8], 
           [7, 8, 2, 1, 0, 5, 6, 0, 9], 
           [0, 6, 0, 2, 7, 8, 1, 3, 5], 
           [3, 2, 1, 0, 4, 6, 8, 9, 7], 
           [8, 0, 4, 9, 1, 3, 5, 0, 6], 
           [5, 9, 6, 8, 2, 0, 4, 1, 3], 
           [9, 1, 7, 6, 5, 2, 0, 8, 0], 
           [6, 0, 3, 7, 0, 1, 9, 5, 2], 
           [2, 5, 8, 3, 9, 4, 7, 6, 0]]

# 숫자가 0인 칸의 위치를 받음
zeros = [(i, j) for i in range(9) for j in range(9) if sudoku[i][j] == 0 ]
print(zeros)



[(0, 0), (1, 4), (1, 7), (2, 0), (2, 2), (3, 3), (4, 1), (4, 7), (5, 5), (6, 6), (6, 8), (7, 1), (7, 4), (8, 8)]


In [11]:
# 섬의 개수

# w, h = map(int, input().split())
# info = []
# for _ in range(h):
#     info.append(list(map(int, input().split()))) 

# ---------------------------------------------------------
def dfs(x, y):
    if x <= -1 or x >= h or y <= -1 or y >= w:
        return False
    if info[x][y] == 1:
        info[x][y] = 0
        dfs(x+1, y)
        dfs(x-1, y)
        dfs(x, y+1)
        dfs(x, y-1)
        return True
    return False    

# ---------------------------------------------------------

w, h = 5, 4
info = [[1, 0, 1, 0, 0], 
        [1, 0, 0, 0, 0], 
        [1, 0, 1, 0, 1], 
        [1, 0, 0, 1, 0]]

# ---------------------------------------------------------
result = 0
for i in range(h):
    for j in range(w):
        if dfs(i,j) == True: result += 1

print(result)

5


In [22]:
# 섬의 개수

while True:
    w, h = map(int, input().split())
    if w == 0 and h == 0: break

    info = []
    for _ in range(h):
        info.append(list(map(int, input().split()))) 

    def dfs(x, y):
        if x <= -1 or x >= h or y <= -1 or y >= w:
            return False
        if info[x][y] == 1:
            info[x][y] = 0
            dfs(x+1, y)
            dfs(x-1, y)
            dfs(x, y+1)
            dfs(x, y-1)
            dfs(x-1, y+1)
            dfs(x+1, y+1)
            dfs(x+1, y-1)
            dfs(x-1, y-1)
            return True
        return False    

    result = 0
    for i in range(h):
        for j in range(w):
            if dfs(i,j) == True: result += 1
    print(result)

IndexError: list index out of range

In [87]:
# 설탕배달
# https://www.acmicpc.net/problem/2839

N = int(input())
# N = 4
# N = 18
# N = 7
# N = 11

n5 = N//5
n3 = N//3

answer = []
for i in range(0, n5+1):
    for j in range(0, n3+1):
        if (i*5)+(j*3) == N : answer.append(i + j)

if len(answer) == 0 : print(-1)
else : print(min(answer))

2
